export interface ServiceSubcategory {
  slug: string;
  name_fi: string;
  description_fi: string;
}

export interface ServiceTemplateDefinition {
  id: string;
  name_fi: string;
  description_fi: string;
  popularity_score: number;
  keywords_fi?: string[];
  subcategory_slug?: string;
}

export interface ServiceCategoryDefinition {
  slug: string;
  name_fi: string;
  question: string;
  description_fi: string;
  hero_image: string;
  trending: string;
  benefits: string[];
  subcategories: ServiceSubcategory[];
  templates: ServiceTemplateDefinition[];
}

export const serviceCatalog: ServiceCategoryDefinition[] = [
  {
    slug: 'siivous',
    name_fi: 'Siivous',
    question: 'Tarvitsetko siivousapua?',
    description_fi: 'Kodin, toimiston ja muuttotilanteiden siivouspalvelut yhdestä paikasta.',
    hero_image: '/images/cleaning.png',
    trending: 'Suosittua juuri nyt: muuttosiivous',
    benefits: [
      'Kertasiivous tai säännöllinen ylläpito',
      'Ikkunat, kylpyhuoneet ja keittiöt samalla käynnillä',
      'Selkeä työn kuvaus ja vertailtavat tarjoukset',
    ],
    subcategories: [
      { slug: 'kotisiivous', name_fi: 'Kotisiivous', description_fi: 'Perussiivous kotiin tai asuntoon.' },
      { slug: 'muuttosiivous', name_fi: 'Muuttosiivous', description_fi: 'Huolellinen siivous ennen luovutusta tai muuton jälkeen.' },
      { slug: 'ikkunanpesu', name_fi: 'Ikkunanpesu', description_fi: 'Ikkunat, puitteet ja karmit puhtaaksi.' },
      { slug: 'toimistosiivous', name_fi: 'Toimistosiivous', description_fi: 'Pienen toimiston tai työtilan siistiminen.' },
      { slug: 'suursiivous', name_fi: 'Suursiivous', description_fi: 'Kausittainen perusteellinen puhdistus.' },
    ],
    templates: [
      {
        id: 'tmpl_siivous_yleissiivous',
        name_fi: 'Yleissiivous',
        description_fi: 'Imurointi, lattioiden pesu, pintojen pyyhintä ja kylpyhuoneen siistiminen.',
        popularity_score: 96,
        keywords_fi: ['siivous', 'yleissiivous', 'kotisiivous'],
        subcategory_slug: 'kotisiivous',
      },
      {
        id: 'tmpl_siivous_muuttosiivous',
        name_fi: 'Muuttosiivous',
        description_fi: 'Perusteellinen siivous tyhjään asuntoon ennen luovutusta tai muuton jälkeen.',
        popularity_score: 93,
        keywords_fi: ['muuttosiivous', 'siivous', 'loppusiivous'],
        subcategory_slug: 'muuttosiivous',
      },
      {
        id: 'tmpl_siivous_ikkunanpesu',
        name_fi: 'Ikkunanpesu',
        description_fi: 'Ikkunoiden, karmien ja puitteiden pesu sisä- ja ulkopuolelta.',
        popularity_score: 88,
        keywords_fi: ['ikkunanpesu', 'ikkunat', 'siivous'],
        subcategory_slug: 'ikkunanpesu',
      },
    ],
  },
  {
    slug: 'kotitalous',
    name_fi: 'Kotitalous',
    question: 'Tarvitsetko arjen kotiapua?',
    description_fi: 'Arjen sujuvoittamiseen tarkoitettu käytännön apu kodissa ja kotona asumisen tueksi.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: kodin järjestely',
    benefits: [
      'Apua kiireiseen arkeen tai tilapäiseen tarpeeseen',
      'Sama tekijä voi hoitaa useita pieniä askareita',
      'Sopii myös seniorin tai läheisen tueksi',
    ],
    subcategories: [
      { slug: 'kodin-jarjestely', name_fi: 'Kodin järjestely', description_fi: 'Kaapit, varastot ja huoneet hallintaan.' },
      { slug: 'pyykkihuolto', name_fi: 'Pyykkihuolto', description_fi: 'Pyykinpesu, kuivatus, viikkaus ja silitys.' },
      { slug: 'ruoanlaittoapu', name_fi: 'Ruoanlaittoapu', description_fi: 'Arjen ruoanlaitto tai aterioiden esivalmistelu.' },
      { slug: 'seniori-apu', name_fi: 'Seniori-apu', description_fi: 'Kevyt tuki kotona asumiseen ja arkeen.' },
      { slug: 'kodin-yleisapu', name_fi: 'Kodin yleisapu', description_fi: 'Pienet askareet saman käynnin aikana.' },
    ],
    templates: [
      {
        id: 'tmpl_kotitalous_jarjestely',
        name_fi: 'Kodin järjestelyapu',
        description_fi: 'Kaappien, varaston, eteisen tai keittiön järjestäminen yhdessä tai avaimet käteen -tyylillä.',
        popularity_score: 90,
        keywords_fi: ['järjestely', 'organisointi', 'kotitalous'],
        subcategory_slug: 'kodin-jarjestely',
      },
      {
        id: 'tmpl_kotitalous_pyykki',
        name_fi: 'Pyykkihuolto',
        description_fi: 'Pyykin pesu, kuivaus, viikkaus ja tarvittaessa kevyt silitys.',
        popularity_score: 82,
        keywords_fi: ['pyykki', 'silitys', 'kotitalousapu'],
        subcategory_slug: 'pyykkihuolto',
      },
      {
        id: 'tmpl_kotitalous_kotiapu',
        name_fi: 'Arjen kotiapu',
        description_fi: 'Useamman pienen kotityön yhdistelmä samalla käynnillä.',
        popularity_score: 85,
        keywords_fi: ['kotiapu', 'kotitalous', 'arkiapu'],
        subcategory_slug: 'kodin-yleisapu',
      },
    ],
  },
  {
    slug: 'kokoonpano',
    name_fi: 'Kokoonpano',
    question: 'Tarvitsetko kokoonpanoapua?',
    description_fi: 'Huonekalujen, säilytysratkaisujen ja laitteiden kokoaminen turvallisesti ja siististi.',
    hero_image: '/images/mountingtv.png',
    trending: 'Suosittua juuri nyt: IKEA-kalusteet',
    benefits: [
      'Nopea apu yksiin tai useampiin kalusteisiin',
      'Kokoonpano valmistajan ohjeiden mukaan',
      'Mahdollisuus yhdistää kokoonpano ja kiinnitys',
    ],
    subcategories: [
      { slug: 'ikea-kokoonpano', name_fi: 'IKEA-kokoonpano', description_fi: 'IKEA-kalusteiden kokoaminen ohjeiden mukaan.' },
      { slug: 'toimistokalusteet', name_fi: 'Toimistokalusteet', description_fi: 'Työpisteet, sähköpöydät ja kaapit käyttövalmiiksi.' },
      { slug: 'sanky-ja-sailytys', name_fi: 'Sängyt ja säilytys', description_fi: 'Sängyt, komerot, hyllyt ja lipastot paikoilleen.' },
      { slug: 'kuntolaitteet', name_fi: 'Kuntolaitteet', description_fi: 'Kotikäyttöiset treenilaitteet koottuna turvallisesti.' },
      { slug: 'ulkokalusteet', name_fi: 'Ulkokalusteet', description_fi: 'Terassi- ja pihakalusteiden kokoaminen.' },
    ],
    templates: [
      {
        id: 'tmpl_kokoonpano_ikea',
        name_fi: 'IKEA-kalusteiden kokoaminen',
        description_fi: 'Hyllyjen, kaappien, sänkyjen ja muiden IKEA-kalusteiden kokoaminen.',
        popularity_score: 97,
        keywords_fi: ['ikea', 'kokoonpano', 'huonekalu'],
        subcategory_slug: 'ikea-kokoonpano',
      },
      {
        id: 'tmpl_kokoonpano_tyopiste',
        name_fi: 'Työpisteen kokoaminen',
        description_fi: 'Sähköpöydän, työtuolin ja tarvikkeiden kokoaminen työvalmiiksi.',
        popularity_score: 84,
        keywords_fi: ['työpiste', 'sähköpöytä', 'kokoonpano'],
        subcategory_slug: 'toimistokalusteet',
      },
      {
        id: 'tmpl_kokoonpano_sanky',
        name_fi: 'Sängyn tai vaatekaapin kokoaminen',
        description_fi: 'Isompien makuuhuonekalusteiden kokoaminen ja loppusäätö.',
        popularity_score: 86,
        keywords_fi: ['sänky', 'vaatekaappi', 'kokoonpano'],
        subcategory_slug: 'sanky-ja-sailytys',
      },
    ],
  },
  {
    slug: 'asennus',
    name_fi: 'Asennus',
    question: 'Tarvitsetko asennusapua?',
    description_fi: 'Valaisimet, verhokiskot, peilit ja muut kodin kiinnitykset paikoilleen huolellisesti.',
    hero_image: '/images/mountingtv.png',
    trending: 'Suosittua juuri nyt: valaisimet',
    benefits: [
      'Selkeät pienasennukset kotiin tai toimistoon',
      'Sopii uusien hankintojen viimeistelyyn',
      'Yhdistä asennus samaan käyntiin muiden pienten töiden kanssa',
    ],
    subcategories: [
      { slug: 'valaisinasennus', name_fi: 'Valaisinasennus', description_fi: 'Katto- ja seinävalaisimien kiinnitys paikoilleen.' },
      { slug: 'verhokiskot', name_fi: 'Verhokiskot ja tangot', description_fi: 'Verhokiskot, tangot ja kaihtimet paikoilleen.' },
      { slug: 'peilit-ja-naulakot', name_fi: 'Peilit ja naulakot', description_fi: 'Peilit, naulakot ja muut seinäkiinnitykset.' },
      { slug: 'kodinkoneet', name_fi: 'Pienet kodinkoneasennukset', description_fi: 'Mikrojen, tv-telineiden ja kevyiden laitteiden asennus.' },
      { slug: 'lapsiturva', name_fi: 'Lapsiturvatuotteet', description_fi: 'Portit, kaappilukot ja muut arjen turvakiinnitykset.' },
    ],
    templates: [
      {
        id: 'tmpl_asennus_valaisin',
        name_fi: 'Valaisimen asennus',
        description_fi: 'Yhden tai useamman valaisimen asennus ja kiinnitys.',
        popularity_score: 91,
        keywords_fi: ['valaisin', 'asennus', 'kiinnitys'],
        subcategory_slug: 'valaisinasennus',
      },
      {
        id: 'tmpl_asennus_verhokisko',
        name_fi: 'Verhokiskon asennus',
        description_fi: 'Verhokiskojen tai tankojen asennus oikeaan mittaan ja korkeuteen.',
        popularity_score: 83,
        keywords_fi: ['verhokisko', 'verhotanko', 'asennus'],
        subcategory_slug: 'verhokiskot',
      },
      {
        id: 'tmpl_asennus_peili',
        name_fi: 'Peilin tai naulakon kiinnitys',
        description_fi: 'Peilin, taulun, naulakon tai muun seinäkiinnityksen turvallinen asennus.',
        popularity_score: 86,
        keywords_fi: ['peili', 'naulakko', 'kiinnitys'],
        subcategory_slug: 'peilit-ja-naulakot',
      },
    ],
  },
  {
    slug: 'korjaukset',
    name_fi: 'Korjaukset',
    question: 'Tarvitsetko korjausapua kotiin?',
    description_fi: 'Pienet korjaukset, säädöt ja huollot, joilla koti pysyy käyttökunnossa.',
    hero_image: '/images/plumber.png',
    trending: 'Suosittua juuri nyt: pienet korjaukset',
    benefits: [
      'Pienet viat kuntoon ilman remonttiprojektia',
      'Sopii vuokra-asuntoihin, omakotitaloihin ja toimistoihin',
      'Kuvaile ongelma tarkasti ja pyydä sopivat tarjoukset',
    ],
    subcategories: [
      { slug: 'seinankiinnitykset', name_fi: 'Seinäkiinnitykset', description_fi: 'Hyllyt, taulut ja pienet seinäkiinnitykset.' },
      { slug: 'ovien-ja-kaappien-saadot', name_fi: 'Ovien ja kaappien säädöt', description_fi: 'Saranoiden kiristys ja ovien oikaisu.' },
      { slug: 'silikonisaumat', name_fi: 'Silikonisaumat', description_fi: 'Keittiön ja kylpyhuoneen silikonien uusinta.' },
      { slug: 'pienet-putkityot', name_fi: 'Pienet putkityöt', description_fi: 'Vuotavat liitokset, tiivisteet ja hanat.' },
      { slug: 'pintapaikkaukset', name_fi: 'Pintapaikkaukset', description_fi: 'Pienten reikien ja kolhujen paikkaus.' },
    ],
    templates: [
      {
        id: 'tmpl_korjaukset_seina',
        name_fi: 'Taulujen ja hyllyjen kiinnitys',
        description_fi: 'Taulut, peilit ja hyllyt paikoilleen seinämateriaalin mukaan.',
        popularity_score: 89,
        keywords_fi: ['hylly', 'taulu', 'kiinnitys', 'korjaus'],
        subcategory_slug: 'seinankiinnitykset',
      },
      {
        id: 'tmpl_korjaukset_silikoni',
        name_fi: 'Silikonisaumojen uusinta',
        description_fi: 'Vanhojen silikonien poisto ja uusien saumojen viimeistely.',
        popularity_score: 81,
        keywords_fi: ['silikoni', 'sauma', 'kylpyhuone'],
        subcategory_slug: 'silikonisaumat',
      },
      {
        id: 'tmpl_korjaukset_pienet',
        name_fi: 'Pienet kodin korjaukset',
        description_fi: 'Useamman pienen vian tai säädön korjaus samalla käynnillä.',
        popularity_score: 87,
        keywords_fi: ['pieni korjaus', 'huolto', 'kodin korjaus'],
        subcategory_slug: 'ovien-ja-kaappien-saadot',
      },
    ],
  },
  {
    slug: 'maalaus',
    name_fi: 'Maalaus',
    question: 'Tarvitsetko maalausapua?',
    description_fi: 'Sisä- ja ulkopintojen maalaus sekä kevyt pintojen ehostus pienempiin projekteihin.',
    hero_image: '/images/pricing/handyman.jpg',
    trending: 'Suosittua juuri nyt: sisämaalaus',
    benefits: [
      'Yhden huoneen tai yksittäisten pintojen siistiminen',
      'Sopii muuton, remontin tai pintojen päivityksen yhteyteen',
      'Mahdollisuus yhdistää pohjatyöt ja paikkaukset',
    ],
    subcategories: [
      { slug: 'sisamaalaus', name_fi: 'Sisämaalaus', description_fi: 'Huoneen tai seinäpinnan maalaus sisätiloissa.' },
      { slug: 'paikkamaalaus', name_fi: 'Paikkamaalaus', description_fi: 'Pienet kolhut, kulumat ja maalipinnan korjaukset.' },
      { slug: 'listat-ja-ovet', name_fi: 'Listat ja ovet', description_fi: 'Listojen, karmien ja ovien maalaus.' },
      { slug: 'ulkomaalaus', name_fi: 'Ulkomaalaus', description_fi: 'Pienet ulkopinnat, aidat ja terassit.' },
      { slug: 'tapetointi', name_fi: 'Tapetointi', description_fi: 'Yksittäisen seinän tai huoneen tapetointi.' },
    ],
    templates: [
      {
        id: 'tmpl_maalaus_huone',
        name_fi: 'Huoneen sisämaalaus',
        description_fi: 'Yhden huoneen seinien maalaus valmiiksi rajattuna työnä.',
        popularity_score: 86,
        keywords_fi: ['sisämaalaus', 'seinän maalaus', 'maalaus'],
        subcategory_slug: 'sisamaalaus',
      },
      {
        id: 'tmpl_maalaus_paikkaus',
        name_fi: 'Paikkamaalaus ja seinän ehostus',
        description_fi: 'Pienet jäljet, reiät ja kulumat kuntoon ennen maalausta tai sellaisenaan.',
        popularity_score: 79,
        keywords_fi: ['paikkamaalaus', 'kolhu', 'seinän korjaus'],
        subcategory_slug: 'paikkamaalaus',
      },
      {
        id: 'tmpl_maalaus_terassi',
        name_fi: 'Terassin tai aidan käsittely',
        description_fi: 'Pienen ulkopinnan öljyäminen, maalaus tai suojaus.',
        popularity_score: 76,
        keywords_fi: ['terassi', 'aita', 'ulkomaalaus'],
        subcategory_slug: 'ulkomaalaus',
      },
    ],
  },
  {
    slug: 'muutto',
    name_fi: 'Muutto',
    question: 'Tarvitsetko muuttoapua?',
    description_fi: 'Muuttojen kantaminen, purku ja pakkausapu yksittäisestä huonekalusta koko asuntoon.',
    hero_image: '/images/movingco.png',
    trending: 'Suosittua juuri nyt: kantaminen',
    benefits: [
      'Apu pieneen tai suurempaan muuttoon',
      'Pakkaus, kantaminen ja purku sovittavissa erikseen',
      'Sopii myös yksittäisten huonekalujen siirtoon',
    ],
    subcategories: [
      { slug: 'kantoapu', name_fi: 'Kantoapu', description_fi: 'Laatikot ja huonekalut autoon tai kotiin.' },
      { slug: 'pakkausapu', name_fi: 'Pakkausapu', description_fi: 'Tavaroiden suojaus, pakkaus ja merkintä.' },
      { slug: 'purkuapu', name_fi: 'Purkuapu', description_fi: 'Tavaroiden purku uuteen asuntoon.' },
      { slug: 'raskaat-esineet', name_fi: 'Raskaat esineet', description_fi: 'Sohvat, kaapit, pesukoneet ja muut painavat tavarat.' },
      { slug: 'sisainen-siirto', name_fi: 'Sisäinen siirto', description_fi: 'Huonekalujen siirto saman kodin sisällä.' },
    ],
    templates: [
      {
        id: 'tmpl_muutto_kantoapu',
        name_fi: 'Muuttoapu ja kantaminen',
        description_fi: 'Kantoapu muuttolaatikoille ja huonekaluille portaissa tai hissitalossa.',
        popularity_score: 95,
        keywords_fi: ['muuttoapu', 'kantaminen', 'muutto'],
        subcategory_slug: 'kantoapu',
      },
      {
        id: 'tmpl_muutto_pakkausapu',
        name_fi: 'Pakkausapu',
        description_fi: 'Tavaroiden suojaaminen, laatikointi ja muuton valmistelu.',
        popularity_score: 84,
        keywords_fi: ['pakkausapu', 'muutto', 'laatikot'],
        subcategory_slug: 'pakkausapu',
      },
      {
        id: 'tmpl_muutto_huonekalusiirto',
        name_fi: 'Huonekalujen siirto',
        description_fi: 'Yhden tai useamman ison huonekalun siirto kodin sisällä tai lähialueella.',
        popularity_score: 83,
        keywords_fi: ['huonekalu', 'siirto', 'muutto'],
        subcategory_slug: 'sisainen-siirto',
      },
    ],
  },
  {
    slug: 'kuljetus',
    name_fi: 'Kuljetus',
    question: 'Tarvitsetko kuljetusapua?',
    description_fi: 'Pienkuljetukset, noudot, kierrätyskuormat ja tavaroiden toimitus joustavasti.',
    hero_image: '/images/movingco.png',
    trending: 'Suosittua juuri nyt: tavaran nouto',
    benefits: [
      'Yksittäiset tavarat tai pienet kuormat',
      'Noudot myymälästä, varastosta tai toiselta yksityiseltä',
      'Kierrätys, lahjoitus ja poiskuljetus onnistuvat samalla',
    ],
    subcategories: [
      { slug: 'pikkukuljetus', name_fi: 'Pikkukuljetus', description_fi: 'Nopea tavaran siirto paikasta toiseen.' },
      { slug: 'nouto-ja-toimitus', name_fi: 'Nouto ja toimitus', description_fi: 'Myymälä- tai verkkokauppanouto kotiin.' },
      { slug: 'kierratyskuorma', name_fi: 'Kierrätyskuorma', description_fi: 'Tarpeettomien tavaroiden kuljetus kierrätykseen.' },
      { slug: 'huonekalukuljetus', name_fi: 'Huonekalukuljetus', description_fi: 'Yksittäinen sohva, pöytä tai muu isompi tavara.' },
      { slug: 'varastokuljetus', name_fi: 'Varastokuljetus', description_fi: 'Tavarat varastoon tai varastosta kotiin.' },
    ],
    templates: [
      {
        id: 'tmpl_kuljetus_pikku',
        name_fi: 'Pikkukuljetus kaupungissa',
        description_fi: 'Pienemmän tavaraerän nouto ja toimitus kaupungin sisällä.',
        popularity_score: 88,
        keywords_fi: ['kuljetus', 'pikkukuljetus', 'nouto'],
        subcategory_slug: 'pikkukuljetus',
      },
      {
        id: 'tmpl_kuljetus_kierratys',
        name_fi: 'Kierrätyskuorma',
        description_fi: 'Tarpeettomien huonekalujen tai tavaroiden poiskuljetus kierrätykseen.',
        popularity_score: 83,
        keywords_fi: ['kierrätys', 'poiskuljetus', 'kuljetus'],
        subcategory_slug: 'kierratyskuorma',
      },
      {
        id: 'tmpl_kuljetus_huonekalu',
        name_fi: 'Huonekalun nouto',
        description_fi: 'Sohvan, pöydän tai muun isomman tavaran nouto ja toimitus.',
        popularity_score: 85,
        keywords_fi: ['huonekalu', 'nouto', 'kuljetus'],
        subcategory_slug: 'huonekalukuljetus',
      },
    ],
  },
  {
    slug: 'puutarha',
    name_fi: 'Puutarha',
    question: 'Tarvitsetko piha- tai puutarha-apua?',
    description_fi: 'Pihan hoito, kausityöt ja pienet ulkotyöt keväästä talveen.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: pihan kevätsiivous',
    benefits: [
      'Kertaluonteinen apu tai koko kauden ylläpito',
      'Sopii pihoihin, mökeille ja taloyhtiöiden pieniin tarpeisiin',
      'Kausityöt helposti näkyviin yhdellä ilmoituksella',
    ],
    subcategories: [
      { slug: 'nurmikonleikkuu', name_fi: 'Nurmikon leikkuu', description_fi: 'Nurmikko, reunat ja kevyt siistiminen.' },
      { slug: 'haravointi', name_fi: 'Haravointi', description_fi: 'Lehdet, oksat ja pihan yleissiivous.' },
      { slug: 'pensaiden-leikkaus', name_fi: 'Pensaiden leikkaus', description_fi: 'Pensasaidat ja koristepensaat kuntoon.' },
      { slug: 'istutukset', name_fi: 'Istutukset', description_fi: 'Kukat, mullat ja pienet pihaprojektit.' },
      { slug: 'lumityot', name_fi: 'Lumityöt', description_fi: 'Lumityöt, hiekoitus ja kulkuväylien avaaminen.' },
    ],
    templates: [
      {
        id: 'tmpl_puutarha_nurmikko',
        name_fi: 'Nurmikon leikkuu',
        description_fi: 'Nurmikon leikkuu, rajaus ja pihan viimeistely samalla käynnillä.',
        popularity_score: 91,
        keywords_fi: ['nurmikko', 'pihanhoito', 'puutarha'],
        subcategory_slug: 'nurmikonleikkuu',
      },
      {
        id: 'tmpl_puutarha_kevatsiivous',
        name_fi: 'Pihan kevät- tai syyssiivous',
        description_fi: 'Lehtien, risujen ja roskien poisto sekä yleinen pihan siistiminen.',
        popularity_score: 86,
        keywords_fi: ['haravointi', 'piha', 'syyssiivous'],
        subcategory_slug: 'haravointi',
      },
      {
        id: 'tmpl_puutarha_pensaat',
        name_fi: 'Pensaiden leikkaus',
        description_fi: 'Pensasaidat ja pensaat siististi takaisin muotoonsa.',
        popularity_score: 80,
        keywords_fi: ['pensaat', 'leikkaus', 'puutarha'],
        subcategory_slug: 'pensaiden-leikkaus',
      },
    ],
  },
  {
    slug: 'it-apu',
    name_fi: 'IT-apu',
    question: 'Tarvitsetko teknistä tukea?',
    description_fi: 'Tietokoneet, verkot ja laitteet käyttökuntoon kotona tai pienessä toimistossa.',
    hero_image: '/images/pricing/womanlaptop.jpg',
    trending: 'Suosittua juuri nyt: wifi-vianhaku',
    benefits: [
      'Apua laitteiden käyttöönottoon ja ongelmatilanteisiin',
      'Sopii kotiin, etätyöhön ja seniorin digitukeen',
      'Moni tehtävä hoituu myös etäopastuksena',
    ],
    subcategories: [
      { slug: 'tietokoneen-kayttoonotto', name_fi: 'Tietokoneen käyttöönotto', description_fi: 'Uusi laite valmiiksi käyttöön.' },
      { slug: 'wifi-vianhaku', name_fi: 'WiFi-vianhaku', description_fi: 'Hitaan tai pätkivän verkon selvitys.' },
      { slug: 'tulostin-ja-oheislaitteet', name_fi: 'Tulostin ja oheislaitteet', description_fi: 'Tulostimet, näytöt ja muut oheislaitteet käyttöön.' },
      { slug: 'puhelinopastus', name_fi: 'Puhelinopastus', description_fi: 'Älypuhelimen tai tabletin perusopastus.' },
      { slug: 'etatyotuki', name_fi: 'Etätyötuki', description_fi: 'Kamerat, kuulokkeet ja työpisteen laitteet kuntoon.' },
    ],
    templates: [
      {
        id: 'tmpl_it_kayttoonotto',
        name_fi: 'Tietokoneen käyttöönotto',
        description_fi: 'Käyttäjätilit, päivitykset, ohjelmat ja perusasetukset kuntoon.',
        popularity_score: 92,
        keywords_fi: ['tietokone', 'käyttöönotto', 'it-apu'],
        subcategory_slug: 'tietokoneen-kayttoonotto',
      },
      {
        id: 'tmpl_it_wifi',
        name_fi: 'WiFi-ongelman ratkaisu',
        description_fi: 'Hitaan tai pätkivän langattoman verkon vianhaku ja optimointi.',
        popularity_score: 90,
        keywords_fi: ['wifi', 'verkko', 'it-apu'],
        subcategory_slug: 'wifi-vianhaku',
      },
      {
        id: 'tmpl_it_tulostin',
        name_fi: 'Tulostimen asennus',
        description_fi: 'Tulostimen, skannerin tai muun oheislaitteen asennus ja testaus.',
        popularity_score: 81,
        keywords_fi: ['tulostin', 'oheislaite', 'it'],
        subcategory_slug: 'tulostin-ja-oheislaitteet',
      },
    ],
  },
  {
    slug: 'lastenhoito',
    name_fi: 'Lastenhoito',
    question: 'Tarvitsetko lastenhoitoapua?',
    description_fi: 'Arjen lastenhoito, iltavuorot ja satunnaiset apukäynnit perheiden tueksi.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: lastenvahti illaksi',
    benefits: [
      'Apu arkeen, juhliin tai lyhytaikaiseen tarpeeseen',
      'Mahdollisuus kuvata lasten iät, aikataulut ja erityistarpeet',
      'Sopii kertakäynteihin tai toistuvaan apuun',
    ],
    subcategories: [
      { slug: 'iltahoito', name_fi: 'Iltahoito', description_fi: 'Lastenvahti illaksi tai viikonlopuksi.' },
      { slug: 'iltapaivahoito', name_fi: 'Iltapäivähoito', description_fi: 'Koulun tai päiväkodin jälkeinen apu.' },
      { slug: 'harrastuksiin-vienti', name_fi: 'Harrastuksiin vienti', description_fi: 'Saattaminen harrastuksiin ja takaisin.' },
      { slug: 'perheen-arki', name_fi: 'Perheen arkiapu', description_fi: 'Yhdistelmä lastenhoitoa ja kevyttä kotiapua.' },
      { slug: 'juhlaillan-lastenvahti', name_fi: 'Juhlaillan lastenvahti', description_fi: 'Tilapäinen hoito tapahtuman tai menon ajaksi.' },
    ],
    templates: [
      {
        id: 'tmpl_lastenhoito_ilta',
        name_fi: 'Lastenvahti illaksi',
        description_fi: 'Luotettava lastenhoitaja muutamaksi tunniksi ilta-aikaan.',
        popularity_score: 90,
        keywords_fi: ['lastenvahti', 'lastenhoito', 'ilta'],
        subcategory_slug: 'iltahoito',
      },
      {
        id: 'tmpl_lastenhoito_iltapaiva',
        name_fi: 'Koululaisen iltapäiväapu',
        description_fi: 'Koulun jälkeinen hoito, välipala ja läksyjen aloitus.',
        popularity_score: 82,
        keywords_fi: ['koululainen', 'iltapäivähoito', 'lastenhoito'],
        subcategory_slug: 'iltapaivahoito',
      },
      {
        id: 'tmpl_lastenhoito_arki',
        name_fi: 'Arjen lastenhoitoapu',
        description_fi: 'Joustava lastenhoitoapu perheen aikataulujen tueksi.',
        popularity_score: 84,
        keywords_fi: ['lastenhoito', 'perhe', 'arki'],
        subcategory_slug: 'perheen-arki',
      },
    ],
  },
  {
    slug: 'lemmikinhoito',
    name_fi: 'Lemmikinhoito',
    question: 'Tarvitsetko lemmikille hoitoa tai ulkoilutusta?',
    description_fi: 'Koirien ulkoilutus, kotikäynnit ja lemmikkien hoito silloin kun itse et ehdi.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: koiran ulkoilutus',
    benefits: [
      'Sopii arkeen, matkoihin ja tilapäisiin menoihin',
      'Kotikäynnit tai sovittu hoito omassa ympäristössä',
      'Kuvaile tarkasti lemmikin rutiinit ja erityistarpeet',
    ],
    subcategories: [
      { slug: 'koiran-ulkoilutus', name_fi: 'Koiran ulkoilutus', description_fi: 'Säännöllinen tai kertaluonteinen ulkoilutus.' },
      { slug: 'kissan-kotikaynti', name_fi: 'Kissan kotikäynti', description_fi: 'Ruokinta, hiekkalaatikko ja seurustelu.' },
      { slug: 'lemmikkivahti', name_fi: 'Lemmikkivahti', description_fi: 'Useamman tunnin tai päivän hoitojärjestely.' },
      { slug: 'ruokinta-ja-laakitys', name_fi: 'Ruokinta ja lääkitys', description_fi: 'Sovittu perushoito kotikäynnin yhteydessä.' },
      { slug: 'lemmikin-kuljetus', name_fi: 'Lemmikin kuljetus', description_fi: 'Kuljetus eläinlääkäriin tai hoitopaikkaan.' },
    ],
    templates: [
      {
        id: 'tmpl_lemmikinhoito_koira',
        name_fi: 'Koiran ulkoilutus',
        description_fi: 'Koiran lenkitys sovitulla kestolla ja rytmillä.',
        popularity_score: 92,
        keywords_fi: ['koira', 'ulkoilutus', 'lemmikinhoito'],
        subcategory_slug: 'koiran-ulkoilutus',
      },
      {
        id: 'tmpl_lemmikinhoito_koti',
        name_fi: 'Lemmikin kotihoito',
        description_fi: 'Kotikäynti kissalle tai koiralle ruokinnan ja perushoidon kanssa.',
        popularity_score: 85,
        keywords_fi: ['lemmikki', 'kotihoito', 'ruokinta'],
        subcategory_slug: 'kissan-kotikaynti',
      },
      {
        id: 'tmpl_lemmikinhoito_vahti',
        name_fi: 'Lemmikkivahti viikonlopuksi',
        description_fi: 'Sovittu hoito viikonlopun tai lyhyen poissaolon ajaksi.',
        popularity_score: 80,
        keywords_fi: ['lemmikkivahti', 'viikonloppu', 'lemmikinhoito'],
        subcategory_slug: 'lemmikkivahti',
      },
    ],
  },
  {
    slug: 'opetus',
    name_fi: 'Opetus',
    question: 'Tarvitsetko opetusta tai digitukea?',
    description_fi: 'Yksityisopetus, läksyapu ja käytännön digituki lapsille, nuorille ja aikuisille.',
    hero_image: '/images/pricing/womanlaptop.jpg',
    trending: 'Suosittua juuri nyt: matematiikan tuki',
    benefits: [
      'Tavoitteellinen tuki kokeisiin, arkeen tai uuteen taitoon',
      'Lähi- tai etäopetus tarpeen mukaan',
      'Selkeä kuvaus lähtötasosta auttaa löytämään sopivan tekijän',
    ],
    subcategories: [
      { slug: 'matematiikka', name_fi: 'Matematiikka', description_fi: 'Tukiopetus alakoulusta lukioon.' },
      { slug: 'kielet', name_fi: 'Kielet', description_fi: 'Englanti, ruotsi ja muut kielet.' },
      { slug: 'digituki', name_fi: 'Digituki', description_fi: 'Tietokoneen, puhelimen ja verkkoasioinnin perusopastus.' },
      { slug: 'opiskelutekniikka', name_fi: 'Opiskelutekniikka', description_fi: 'Ajankäyttö, rutiinit ja opiskelun tuki.' },
      { slug: 'ohjelmisto-opastus', name_fi: 'Ohjelmisto-opastus', description_fi: 'Toimisto-ohjelmat, etäpalaverit ja perussovellukset.' },
    ],
    templates: [
      {
        id: 'tmpl_opetus_matematiikka',
        name_fi: 'Matematiikan tukiopetus',
        description_fi: 'Tuki läksyihin, kokeisiin tai yksittäiseen aiheeseen.',
        popularity_score: 87,
        keywords_fi: ['matematiikka', 'tukiopetus', 'opetus'],
        subcategory_slug: 'matematiikka',
      },
      {
        id: 'tmpl_opetus_kielet',
        name_fi: 'Englannin keskusteluapu',
        description_fi: 'Rento mutta tavoitteellinen tuki puhumiseen ja ymmärtämiseen.',
        popularity_score: 78,
        keywords_fi: ['englanti', 'kieli', 'opetus'],
        subcategory_slug: 'kielet',
      },
      {
        id: 'tmpl_opetus_digituki',
        name_fi: 'Digituki kotona',
        description_fi: 'Apua verkkopalveluihin, sähköpostiin ja laitteen käyttöön.',
        popularity_score: 85,
        keywords_fi: ['digituki', 'tietokoneapu', 'opastus'],
        subcategory_slug: 'digituki',
      },
    ],
  },
  {
    slug: 'valokuvaus',
    name_fi: 'Valokuvaus',
    question: 'Tarvitsetko kuvaajaa tai visuaalista sisältöä?',
    description_fi: 'Kuvauspalvelut perheille, tapahtumiin, asuntoihin ja pienyritysten tarpeisiin.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: tapahtumakuvaus',
    benefits: [
      'Pienet keikat ja paikalliset kuvaukset helposti näkyviin',
      'Sopii yksityisiin juhliin ja yritysten arkeen',
      'Voit pyytää samalla myös kevyttä editointia',
    ],
    subcategories: [
      { slug: 'perhekuvaus', name_fi: 'Perhekuvaus', description_fi: 'Perhe- ja parikuvaukset luonnollisesti.' },
      { slug: 'tapahtumakuvaus', name_fi: 'Tapahtumakuvaus', description_fi: 'Juhlat, valmistujaiset ja pienet tapahtumat.' },
      { slug: 'tuotekuvaus', name_fi: 'Tuotekuvaus', description_fi: 'Verkkokaupan tai somen tuotekuvat.' },
      { slug: 'asuntokuvaus', name_fi: 'Asuntokuvaus', description_fi: 'Asunnon tai tilan myynti- ja vuokrakuvat.' },
      { slug: 'sisallontuotanto', name_fi: 'Sisällöntuotanto', description_fi: 'Kuvapaketti someen tai verkkosivulle.' },
    ],
    templates: [
      {
        id: 'tmpl_valokuvaus_perhe',
        name_fi: 'Perhe- tai parikuvaus',
        description_fi: 'Rento kuvaus ulkona tai kotona valmiilla lopputuloksella.',
        popularity_score: 82,
        keywords_fi: ['perhekuvaus', 'parikuvaus', 'valokuvaus'],
        subcategory_slug: 'perhekuvaus',
      },
      {
        id: 'tmpl_valokuvaus_tapahtuma',
        name_fi: 'Tapahtumakuvaus',
        description_fi: 'Pienet juhlat, valmistujaiset tai yrityksen tilaisuus dokumentoituna.',
        popularity_score: 86,
        keywords_fi: ['tapahtumakuvaus', 'juhlat', 'kuvaus'],
        subcategory_slug: 'tapahtumakuvaus',
      },
      {
        id: 'tmpl_valokuvaus_tuote',
        name_fi: 'Tuotekuvaus',
        description_fi: 'Selkeät tuotekuvat verkkokauppaan, someen tai katalogiin.',
        popularity_score: 76,
        keywords_fi: ['tuotekuvaus', 'verkkokauppa', 'sisältö'],
        subcategory_slug: 'tuotekuvaus',
      },
    ],
  },
  {
    slug: 'suunnittelu',
    name_fi: 'Suunnittelu',
    question: 'Tarvitsetko suunnittelu- tai sisältöapua?',
    description_fi: 'Kevyt graafinen suunnittelu, somepohjat, logot ja pienet sisältöprojektit.',
    hero_image: '/images/pricing/womanlaptop.jpg',
    trending: 'Suosittua juuri nyt: somepohjat',
    benefits: [
      'Pienet projektit ilman raskasta toimistoprosessia',
      'Sopii yrittäjälle, yhdistykselle tai yksityiselle',
      'Voit pyytää samalla myös teksti- tai sisältöapua',
    ],
    subcategories: [
      { slug: 'logot-ja-ilme', name_fi: 'Logot ja ilme', description_fi: 'Logo, värit ja perusbrändi alkuun.' },
      { slug: 'somepohjat', name_fi: 'Somepohjat', description_fi: 'Instagram-, Facebook- ja mainospohjat.' },
      { slug: 'esitteet-ja-flyerit', name_fi: 'Esitteet ja flyerit', description_fi: 'Paino- tai pdf-materiaalit käyttövalmiiksi.' },
      { slug: 'cv-ja-portfolio', name_fi: 'CV ja portfolio', description_fi: 'Selkeä ja moderni työnhakumateriaali.' },
      { slug: 'sisaltosuunnittelu', name_fi: 'Sisältösuunnittelu', description_fi: 'Kevyt kampanja- tai julkaisusuunnitelma.' },
    ],
    templates: [
      {
        id: 'tmpl_suunnittelu_logo',
        name_fi: 'Logon suunnittelu',
        description_fi: 'Kevyt logo- ja ilmeprojekti yritykselle, toiminimelle tai yhdistykselle.',
        popularity_score: 84,
        keywords_fi: ['logo', 'graafinen suunnittelu', 'ilme'],
        subcategory_slug: 'logot-ja-ilme',
      },
      {
        id: 'tmpl_suunnittelu_some',
        name_fi: 'Some-kuvapohjat',
        description_fi: 'Julkaisupohjat ja visuaalinen linja somesisältöihin.',
        popularity_score: 81,
        keywords_fi: ['some', 'kuvapohja', 'suunnittelu'],
        subcategory_slug: 'somepohjat',
      },
      {
        id: 'tmpl_suunnittelu_esite',
        name_fi: 'Esite tai flyer',
        description_fi: 'Yhden materiaalin suunnittelu valmiiseen käyttöön tai painoon.',
        popularity_score: 75,
        keywords_fi: ['esite', 'flyer', 'suunnittelu'],
        subcategory_slug: 'esitteet-ja-flyerit',
      },
    ],
  },
  {
    slug: 'asiointiapu',
    name_fi: 'Asiointiapu',
    question: 'Tarvitsetko käytännön asiointiapua?',
    description_fi: 'Kauppa-apu, noudot, saattaminen ja muut käytännön arjen asiat silloin kun itse et ehdi.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: kauppa-apu',
    benefits: [
      'Apu yksittäiseen asiointiin tai toistuvaan tarpeeseen',
      'Sopii myös läheisen tai seniorin tueksi',
      'Tarkka tehtävän kuvaus helpottaa oikean tekijän valintaa',
    ],
    subcategories: [
      { slug: 'kauppa-apu', name_fi: 'Kauppa-apu', description_fi: 'Ruokaostokset tai päivittäiset hankinnat puolestasi.' },
      { slug: 'noutopalvelu', name_fi: 'Noutopalvelu', description_fi: 'Tavaroiden, tilausten tai asiakirjojen nouto.' },
      { slug: 'saattaja-apu', name_fi: 'Saattaja-apu', description_fi: 'Saattaminen asioille, tapaamisiin tai palveluihin.' },
      { slug: 'jonotusapu', name_fi: 'Jonotusapu', description_fi: 'Apu aikaa vieviin noutoihin tai palvelupisteisiin.' },
      { slug: 'apteekki-ja-posti', name_fi: 'Apteekki ja posti', description_fi: 'Kevyt asiointi virastoissa, apteekissa tai postissa.' },
    ],
    templates: [
      {
        id: 'tmpl_asiointi_kauppa',
        name_fi: 'Kauppa- ja asiointiapu',
        description_fi: 'Apua kauppaan, apteekkiin tai muuhun päivittäiseen asiointiin.',
        popularity_score: 80,
        keywords_fi: ['asiointi', 'kauppa-apu', 'apu'],
        subcategory_slug: 'kauppa-apu',
      },
      {
        id: 'tmpl_asiointi_nouto',
        name_fi: 'Nouto ja toimitus',
        description_fi: 'Tilauksen, asiakirjan tai tavaran nouto sovitusti.',
        popularity_score: 79,
        keywords_fi: ['nouto', 'toimitus', 'asiointiapu'],
        subcategory_slug: 'noutopalvelu',
      },
      {
        id: 'tmpl_asiointi_saattaja',
        name_fi: 'Saattaja tai asiointituki',
        description_fi: 'Tuki käynneille, tapaamisiin tai kodin ulkopuoliseen asiointiin.',
        popularity_score: 77,
        keywords_fi: ['saattaja', 'asiointituki', 'apu'],
        subcategory_slug: 'saattaja-apu',
      },
    ],
  },
  {
    slug: 'juhlat',
    name_fi: 'Juhlat ja tapahtumat',
    question: 'Tarvitsetko apua juhliin tai tapahtumaan?',
    description_fi: 'Koristelu, tarjoiluapu, valmistelu ja purku yksityisiin juhliin tai pieniin tilaisuuksiin.',
    hero_image: '/images/hero/hero-home-services.jpg',
    trending: 'Suosittua juuri nyt: tarjoiluapu',
    benefits: [
      'Apua ennen tapahtumaa, sen aikana tai lopuksi',
      'Sopii synttäreihin, valmistujaisiin ja yritystilaisuuksiin',
      'Voit yhdistää samaan ilmoitukseen useita työvaiheita',
    ],
    subcategories: [
      { slug: 'koristelu', name_fi: 'Koristelu', description_fi: 'Tilojen koristelu ja valmistelu juhlaan.' },
      { slug: 'tarjoiluapu', name_fi: 'Tarjoiluapu', description_fi: 'Apu tarjoiluun, kattaukseen ja keittiöön.' },
      { slug: 'purku-ja-siivous', name_fi: 'Purku ja siivous', description_fi: 'Jälkien siivous ja tilan palautus.' },
      { slug: 'ovimies-ja-vastaanotto', name_fi: 'Vastaanottoapu', description_fi: 'Vieraat vastaan, narikka tai ilmoittautuminen.' },
      { slug: 'juhlapaikan-jarjestely', name_fi: 'Tilan järjestely', description_fi: 'Pöydät, tuolit ja somistus paikoilleen.' },
    ],
    templates: [
      {
        id: 'tmpl_juhlat_avustaja',
        name_fi: 'Juhla-avustaja',
        description_fi: 'Yleinen apu yksityisjuhlaan tai pieneen tapahtumaan.',
        popularity_score: 78,
        keywords_fi: ['juhlat', 'tapahtuma', 'avustaja'],
        subcategory_slug: 'juhlapaikan-jarjestely',
      },
      {
        id: 'tmpl_juhlat_tarjoilu',
        name_fi: 'Tarjoiluapu',
        description_fi: 'Kattaus, keittiöapu ja tarjoilu juhlan aikana.',
        popularity_score: 82,
        keywords_fi: ['tarjoilu', 'juhlat', 'apu'],
        subcategory_slug: 'tarjoiluapu',
      },
      {
        id: 'tmpl_juhlat_purku',
        name_fi: 'Tilan valmistelu ja purku',
        description_fi: 'Juhlatilan järjestely ennen tapahtumaa ja purku sen jälkeen.',
        popularity_score: 75,
        keywords_fi: ['juhlatila', 'purku', 'koristelu'],
        subcategory_slug: 'purku-ja-siivous',
      },
    ],
  },
  {
    slug: 'muu',
    name_fi: 'Muu apu',
    question: 'Tarvitsetko apua, joka ei sovi valmiisiin luokkiin?',
    description_fi: 'Yksilölliset tehtävät, yhdistelmätyöt ja vaikeasti luokiteltavat toimeksiannot.',
    hero_image: '/images/handyman.png',
    trending: 'Suosittua juuri nyt: monipuolinen apukäynti',
    benefits: [
      'Kuvaa tarve omin sanoin ilman pakkoa sopia muottiin',
      'Sopii useamman pienen työn yhdistelmiin',
      'Hyvä vaihtoehto, kun työ vaatii eri osa-alueiden yhdistämistä',
    ],
    subcategories: [
      { slug: 'yhdistelmatyo', name_fi: 'Yhdistelmätyö', description_fi: 'Useita pieniä tehtäviä samassa käynnissä.' },
      { slug: 'erikoispyynto', name_fi: 'Erikoispyyntö', description_fi: 'Tavallisuudesta poikkeava tai yksilöllinen tehtävä.' },
      { slug: 'pikainen-apu', name_fi: 'Pikainen apu', description_fi: 'Nopea apu yksittäiseen tilanteeseen.' },
      { slug: 'selvitettava-tyo', name_fi: 'Selvitettävä työ', description_fi: 'Työ, jonka laajuus tarkentuu keskustelussa.' },
    ],
    templates: [
      {
        id: 'tmpl_muu_yhdistelma',
        name_fi: 'Monipuolinen apu',
        description_fi: 'Useamman arjen tehtävän yhdistelmä saman tekijän kanssa.',
        popularity_score: 74,
        keywords_fi: ['muu apu', 'monipuolinen', 'yhdistelmätyö'],
        subcategory_slug: 'yhdistelmatyo',
      },
      {
        id: 'tmpl_muu_kaynti',
        name_fi: 'Usean tehtävän apukäynti',
        description_fi: 'Yksi käynti, useita pieniä töitä tai selvitystä vaativia asioita.',
        popularity_score: 72,
        keywords_fi: ['apukäynti', 'muu työ', 'sekalainen apu'],
        subcategory_slug: 'selvitettava-tyo',
      },
      {
        id: 'tmpl_muu_erikoinen',
        name_fi: 'Muu yksilöllinen työ',
        description_fi: 'Kerro omin sanoin mitä tarvitset, niin tekijät voivat ehdottaa toteutusta.',
        popularity_score: 70,
        keywords_fi: ['erikoispyyntö', 'muu', 'yksilöllinen'],
        subcategory_slug: 'erikoispyynto',
      },
    ],
  },
];

export const serviceCatalogBySlug = Object.fromEntries(
  serviceCatalog.map((category) => [category.slug, category])
) as Record<string, ServiceCategoryDefinition>;

export const serviceCategorySlugs = serviceCatalog.map((category) => category.slug);

export const topLevelCategoryNames = serviceCatalog.map((category) => category.name_fi);
